AWSTemplateFormatVersion: 2010-09-09
Description: lecture10-ALB-template


Parameters:
  NameBase:
    Description: this is base name.
    Type: String
    Default: "RaiseTech"

Resources:
  #ALB---------------------------------------------------------------------
  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      IpAddressType: ipv4
      Name: !Sub "${NameBase}-ALB"
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue RaiseTech-ALBSG-ID
      SubnetMappings:
        - SubnetId: !ImportValue RaiseTech-MyPublicSubnet1-ID
        - SubnetId: !ImportValue RaiseTech-MyPublicSubnet2-ID
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-ALB"

  #TargetGroup--------------------------------------------------------------
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue RaiseTech-VPC-ID
      IpAddressType: ipv4
      Protocol: HTTP  #ヘルスチェックを行う際のプロトコル
      ProtocolVersion: HTTP1
      Port: 80
      TargetType: instance
      Targets:
        - Id: !ImportValue RaiseTech-EC2-ID
          Port: 80
      HealthCheckEnabled: true                        #ヘルスチェック有効化
      HealthCheckIntervalSeconds: 60                  #ヘルスチェックの間隔
      HealthCheckPath: /
      HealthCheckPort: traffic-port  #ヘルスチェックを行う際に使用するポート
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Name
          Value: !Sub "${NameBase}-ALBTG"

  #Listener-----------------------------------------------------------------
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener    
    Properties:
      Port: 80
      Protocol: HTTP
      DefaultActions:
         - TargetGroupArn: !Ref MyTargetGroup
           Type: forward
      LoadBalancerArn: !Ref MyALB

Outputs:
  #output-------------------------------------------------------------------
  MyEC2:
    Value: !Ref MyALB
    Export:
      Name: !Sub "${NameBase}-ALB-ID"
