AWSTemplateFormatVersion: 2010-09-09
Description: lecture10-RDS-template



Parameters:
  #RDS----------------------------------------------------------------------
  RDSName: 
   Type: String
   Default:
  
  RDSAZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: ap-northeast-1a
  
  RDSMasterUserPassword: 
    Type: String
    Default: adminadmin
  
  RDSSubnetGroupName: 
   Type: String
   Default:

    
 
Resources:
  #RDS----------------------------------------------------------------------
  MyRDS:
   Type: AWS::RDS::DBInstance
   DeletionPolicy: Delete
   UpdateReplacePolicy: Delete
   Properties:
     AvailabilityZone: !Ref RDSAZ
     DBInstanceIdentifier: !Ref RDSName   
     DBSubnetGroupName: !Ref RDSSubnetGroup
     DBInstanceClass: db.t2.micro
     AllocatedStorage: 20
     Engine: mysql
     StorageType: gp2
     MasterUsername: admin
     MasterUserPassword: !Ref RDSMasterUserPassword
     CopyTagsToSnapshot: false
     DeleteAutomatedBackups: true
     PubliclyAccessible: false
     MultiAZ: false
     VPCSecurityGroups: 
       - !ImportValue RDSSG
     Tags:
       - Key: Name
         Value: !Ref RDSName 
         
         

  #RDSubnetgroup------------------------------------------------------------
  RDSSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupName: !Ref RDSSubnetGroupName
      SubnetIds:
        - !ImportValue MyPrivateSubnet1
        - !ImportValue MyPrivateSubnet2
  
  
Outputs:
  RDS:
    Value: !Ref MyRDS
    Export:
      Name: !Ref RDSName 
 
 
 
