AWSTemplateFormatVersion: 2010-09-09
Description: lecture10-SecurityGroup-template



Parameters:
  MyIP:
    Description: IP address allowed to access EC2
    Type: String
   

 
Resources:
  #EC2SG----------------------------------------------------------------------
  MyEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MyEC2SG
      GroupDescription: EC2-sg
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup



  
Outputs:
　#output-------------------------------------------------------------------
  MyEC2:
    Value: !Ref MyEC2
    Export:
      Name: !Ref EC2Name
  
  
 
