----
- name: check nginx install
  shell: bash -lc "nginx -v"
  register: check_nginx_installed
  changed_when: no
  ignore_errors: yes

- name: nginx install
  become_user: root
  shell: bash -lc "amazon-linux-extras install -y nginx1"
  when: check_nginx_installed is failed

- name: create rails.conf
  become_user: root
  template:
    src: rails.conf.j2
    dest: "/etc/nginx/conf.d/rails.conf"

- name: start nginx
  systemd:
    name: nginx
    state: started
  register: start_nginx
  become: yes

- name: start unicorn
  shell: bash -lc "bundle exec unicorn_rails -c config/unicorn.rb -E development -D"
  args: 
    chdir: "{{ app_home }}"
  when: start_nginx.changed
