AWSTemplateFormatVersion: 2010-09-09
Description: lecture10-RDS-template


Parameters:
  #RDS----------------------------------------------------------------------
  RDSName:
   Type: String
   Default: "RaiseTech-RDS"

  RDSAZ:
    Type: AWS::EC2::AvailabilityZone::Name
    Default: "ap-northeast-1a"

  RDSMasterUserPassword:
    Type: String
    Default: "adminadmin"

  RDSSubnetGroupName:
   Type: String
   Default: "RaiseTech-RDSSubnetGroup"

Resources:
  #RDSubnetgroup------------------------------------------------------------
  MyRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "RDSSubnetGroup"
      DBSubnetGroupName: !Ref RDSSubnetGroupName
      SubnetIds:
        - !ImportValue RaiseTech-PrivateSubnet1
        - !ImportValue RaiseTech-PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Ref RDSSubnetGroupName

  #RDS----------------------------------------------------------------------
  MyRDS:
   Type: AWS::RDS::DBInstance
   DeletionPolicy: Delete
   UpdateReplacePolicy: Delete
   Properties:
     AvailabilityZone: !Ref RDSAZ
     DBInstanceIdentifier: !Ref RDSName
     VPCSecurityGroups:
       - !ImportValue RaiseTech-RDSSG
     DBSubnetGroupName: !Ref MyRDSSubnetGroup
     DBInstanceClass: db.t2.micro
     AllocatedStorage: 20
     Engine: mysql
     StorageType: gp2
     MasterUsername: admin
     MasterUserPassword: !Ref RDSMasterUserPassword
     CopyTagsToSnapshot: false                             #スナップショットにタグを関連付ける
     DeleteAutomatedBackups: true                          #RDS削除時に生成されるスナップショットの削除
     PubliclyAccessible: false
     MultiAZ: false
     Tags:
       - Key: Name
         Value: !Ref RDSName

Outputs:
  MyRDS:
    Value: !Ref MyRDS
    Export:
      Name: !Ref RDSName
