- hosts:
    - web-server
  become: True
  become_user: ec2-user
  roles:
    - { role: 01_yum, tags: yum }
    - { role: 02_ruby, tags: ruby }
    - { role: 03_rails, tags: rails }
    - { role: 04_node, tags: node }
    - { role: 05_yarn, tags: yarn }
    - { role: 06_bundler, tags: bundler }
    - { role: 07_mysql, tags: mysql }
    - { role: 08_app, tags: app }
    - { role: 09_nginx, tags: nginx }
  vars:
#    sample_app_dir: /var/www/raisetech-live8-sample-app
#    aws_db_user: "{{ (lookup('env','AWS_DB_USER')) }}"
#    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"
#    aws_db_host : "{{ (lookup('env','AWS_DB_HOST')) }}"
#    aws_s3_access_key : "{{ (lookup('env','AWS_S3_ACCESS_KEY')) }}"
#    aws_s3_secret_access_key: "{{ (lookup('env','AWS_S3_SECRET_ACCESS_KEY')) }}"
#    aws_s3_bucket: "{{ (lookup('env','AWS_S3_BUCKET')) }}"