---
# rbenv------------------------------------------------------------
- name: check rbenv install
  shell: bash -lc "rbenv --version"
  register: check_rbenv_installed
  changed_when: no
  ignore_errors: yes

- name: install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: check_rbenv_installed is failed

- name: Add rbenv to PATH
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: check_rbenv_installed is failed

- name: eval rbenv init
  lineinfile: 
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
  when: check_rbenv_installed is failed
  
- name: load .bash_profile
  shell: bash -lc "source ~/.bash_profile"
  when: check_rbenv_installed is failed

# ruby------------------------------------------------------------
- name: install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: rbenv_installed is failed

- name: check ruby install
  shell: bash -lc "rbenv version | grep {{ ruby_version }}"
  register: check_ruby_installed
  changed_when: no
  ignore_errors: yes

- name: install ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: check_ruby_installed is failed

- name: rehash rbenv
  shell: bash -lc "rbenv rehash"
  when: check_ruby_installed is failed

- name: set default ruby version
  shell: bash -lc "rbenv global {{ ruby_version }}"
  when: ruby_installed is failed

